config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/show'
  post 'resumes/create'
  delete 'resumes/destroy'
  root to: 'home#index'
  resources :projects
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :resumes
  root 'resumes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :desc, :hosted_url, :github_url, presence: true
end

app/models/resume.rb
class Resume < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/' if current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.all
    @resumes = Resume.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize

  def index
    @projects = Project.all.order(:id)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to '/projects'
    else
      redirect_to 'projects/new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)

    redirect_to '/projects'
  end

  private

  def project_params
    params.require(:project).permit(:name,
                                    :desc,
                                    :img,
                                    :hosted_url,
                                    :github_url,
                                    :active)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'resume' # Excluding ".pdf" extension.
      end
    end
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render 'new'
    end
  end

  def edit
    @resume = Resume.find(params[:id])
  end

  def update
    @resume = Resume.find(params[:id])
    @resume.update(resume_params)

    redirect_to '/resumes'
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice: "The resume #{@resume.name} has been deleted."
  end

  private

  def resume_params
    params.require(:resume).permit(:name, :attachment, :active)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:login][:username])
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to '/projects'
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admins/new.html.erb
<%= form_for @admin do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username, autofocus: true %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/home/index.html.erb
<% if current_user %>
  <%= button_to "Logout", logout_path, method: :get %>
  <%= button_to "Access projects", projects_path, method: :get %>
  <%= button_to "Access resumes", resumes_path, method: :get %>
<% end %>

<div class="landing">
  <div class="text-container">
    <div class="container">
      <div class="logo">
        Luis Senior
        <div class="text">
          <span class="word">Software </span><span class="web">Engineer</span>
        </div>
      </div>
    </div>
    <a href="https://www.github.com/Heybluguy"><i class="fab fa-github-square fa-3x"></i></a>
    <a href="mailto:luisarturosenior@gmail.com"><i class="fas fa-envelope fa-3x"></i></a>
    <a href="https://www.linkedin.com/in/luissenior/"><i class="fab fa-linkedin fa-3x"></i></a>
  </div>
  <div class="arrow bounce">
    <a class="fa fa-arrow-down fa-2x" href="#projects"></a>
  </div>
</div>

<div class="project-section">

  <a id="projects"><h1>Projects</h1></a>
  <div class="project-list">
    <% @projects.where(:active => true).each do |project| %>
    <div class="project">
      <h2><%= project.name %></h2>
      <%= image_tag(project.img) if project.img? %>
      <p class="desc">
        <%= project.desc %>
      </p>
      <div class="buttons">
        <button><%= link_to 'Demo', project.hosted_url, target: '_blank' %></button>
        <button><%= link_to 'Repo', project.github_url, target: '_blank' %></button>
      </div>
    </div>
    <% end %>
  </div>
</div>

<!--div class="resume-section">

  <a id="resume"><h1>Resume</h1></a>
    <div class="resume">
      <% @resumes.where(:active => true).each do |resume| %>
        <iframe src=<%= resume.attachment_url  %> width="400em" height="580em"> </iframe><br>

        <a href=<%= resume.attachment_url  %>>Download the PDF</a>.</p>
         <div class="arrow bounce link">
        <%= link_to "View Resume", resume.attachment_url %>
        </div>
      <% end %>


    </div>

</div-->

<div class="skill-section">

  <a id="skills"><h1>Skills</h1></a>
    <div class="skill-list">
      <div class="skill"><i class="devicon-ruby-plain-wordmark" data-toggle="tooltip" title="Ruby"></i></div>
      <div class="skill" ><i class="devicon-rails-plain-wordmark" data-toggle="tooltip" title="RoR"></i></div>
      <div class="skill"><i class="devicon-postgresql-plain-wordmark" data-toggle="tooltip" title="Postgre SQL"></i></i></div>
      <!--div class="skill"><i class="devicon-mysql-plain-wordmark" data-toggle="tooltip" title="mySQL"></i></i></div-->
      <div class="skill"><i class="devicon-heroku-plain-wordmark" data-toggle="tooltip" title="Heroku"></i></div>
      <div class="skill"><i class="devicon-html5-plain-wordmark" data-toggle="tooltip" title="HTML 5"></i></div>
      <div class="skill"> <i class="devicon-css3-plain-wordmark" data-toggle="tooltip" title="CSS 3"></i></div>
      <div class="skill" ><i class="devicon-javascript-plain" data-toggle="tooltip" title="JavaScript"></i></div>
      <div class="skill"> <i class="devicon-bootstrap-plain-wordmark" data-toggle="tooltip" title="Bootstrap"> </i></div>
      <div class="skill"> <i class="devicon-sass-original" data-toggle="tooltip" title="SaSS" > </i></div>
      <div class="skill"> <i class="devicon-wordpress-plain-wordmark" data-toggle="tooltip" title="WordPress" > </i></div>
    </div>

</div>


<footer>
  <a href="https://www.github.com/Heybluguy"><i class="fab fa-github-square fa-2x"></i></a>
  <a href="mailto:luisarturosenior@gmail.com"><i class="fas fa-envelope fa-2x"></i></a>
  <a href="https://www.linkedin.com/in/luissenior/"><i class="fab fa-linkedin fa-2x"></i></a>
  <p>
    luisarturosenior@gmail.com
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luis Senior</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.11/css/all.css" integrity="sha384-p2jx59pefphTFIpeqCcISO9MdVfIm4pNnsL08A6v5vaQc4owkQqxMV8kg4Yvhaw/" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<div class="form-container">
  <div class="form">
    <h3>Edit <%= @project.name %></h3>
    <%= form_for @project do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </div>
      <div class="description">
        <%= f.label :description %>
        <%= f.text_area :desc, cols: "60", rows: "10" %>
      </div>
      <div>
        <%= f.label :img %>
        <%= f.text_field :img %>
      </div>
      <div>
        <%= f.label :hosted_url %>
        <%= f.text_field :hosted_url %>
      </div>
      <div>
        <%= f.label :github_url %>
        <%= f.text_field :github_url %>
      </div>
      <div>
        <%= f.label :active %>
        <%= f.check_box :active %>
      </div>
      <div>
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<%= button_to "Logout", logout_path, method: :get %>
<%= button_to "Portfolio", root_path, method: :get %>
<%= button_to "Add new project", new_project_path, method: :get %>

<table>
  <tr>
    <th>Name</th>
    <th>Active?</th>
    <th><i class="material-icons">edit</i></th>
  </tr>
  <% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.active %></td>
    <td><%= button_to "Edit", edit_project_path(project.id), method: :get %></td>
  </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<div class="form-container">
  <div class="form">
    <%= form_for @project do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </div>
      <div class="description">
        <%= f.label :description %>
        <%= f.text_area :desc, cols: "60", rows: "10" %>
      </div>
      <div>
        <%= f.label :img %>
        <%= f.text_field :img %>
      </div>
      <div>
        <%= f.label :hosted_url %>
        <%= f.text_field :hosted_url %>
      </div>
      <div>
        <%= f.label :github_url %>
        <%= f.text_field :github_url %>
      </div>
      <div>
        <%= f.label :active %>
        <%= f.check_box :active %>
      </div>
      <div>
        <%= f.submit "Create" %>
      </div>
    <% end %>
  </div>
</div>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/edit.html.erb
<div class="form-container">
  <div class="form">
    <%= form_for @resume, html: { multipart: true } do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </div>
      <div>
        <%= f.label :attachment %>
        <%= f.file_field :attachment %>
      </div>
      <div>
        <%= f.label :active %>
        <%= f.check_box :active %>
      </div>
      <div>
        <%= f.submit "Save" %>
      </div>
    <% end %>
  </div>
</div>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>
<%= button_to "Logout", logout_path, method: :get %>
<%= button_to "Portfolio", root_path, method: :get %>
<%= button_to "Add resume", new_resume_path, method: :get %>

<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Download Link</th>
    <th>Active?</th>
    <th><i class="material-icons">edit</i></th>
    <th><i class="material-icons">delete</i></th>
    <% @resumes.each do |resume| %>
      <tr>
      <td></td>
        <td><%= resume.name %></td>
        <td><%= link_to "View Resume", resume.attachment_url %></td>
        <td><%= resume.active %></td>
        <td><%= button_to "Edit", edit_resume_path(resume.id), method: :get %></td>
        <td><%= button_to "Delete",  resume, method: :delete, class: "btn-danger delete", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
      </tr>
    <% end %>
  </tr>
</table>

app/views/resumes/new.html.erb
<%= button_to "Logout", logout_path, method: :get %>
<%= button_to "Portfolio", root_path, method: :get %>
<%= button_to "Add resume", new_resume_path, method: :get %>

<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>

<div class="form-container">
  <div class="form">
    <%= form_for @resume, html: { multipart: true } do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </div>
      <div>
        <%= f.label :attachment %>
        <%= f.file_field :attachment %>
      </div>
      <div>
        <%= f.submit "Save" %>
      </div>
    <% end %>
  </div>
</div>